config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Changed root for cities
  root 'cities#index'

  # States
  get '/states', to: 'states#index'

  # Cities
  get '/cities', to: 'cities#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# Default Application model
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cities
#
#  id       :integer      not null, primary key
#  name     :string       not null
#  state    :state        not null
#  capital  :boolean      default(FALSE)
class City < ApplicationRecord
  scope :state_capital, -> { where(capital: true) }
  validates :name, presence: true
  validates :capital, presence: true
  validates :state, presence: true

  belongs_to :state
end

app/models/state.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: states
#
#  id       :integer      not null, primary key
#  name     :string       not null
#  symbol   :string       not null
class State < ApplicationRecord
  validates :name, presence: true
  validates :symbol, presence: true

  has_many :city, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Default application controller
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

# City model controller
class CitiesController < ApplicationController
  def index
    @cities = City.all

    return unless params[:search_by_name] && params[:search_by_name] != ''

    search_by_name

    return unless params[:search_by_state] && params[:search_by_state] != ''

    search_by_state
  end

  private

  def search_by_name
    @cities = City.where('cities.name ilike ?', "%#{params[:search_by_name]}%")
  end

  def search_by_state
    @cities = City.joins('INNER JOIN states ON states.id = cities.state_id').where(
      'states.symbol ilike ? or states.name ilike ?', "%#{params[:search_by_state]}%", "%#{params[:search_by_state]}%"
    )
  end
end

app/controllers/states_controller.rb
# frozen_string_literal: true

# State model controller
class StatesController < ApplicationController
  def index
    @states = State.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Default application helper
module ApplicationHelper
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

# Cities Helper
module CitiesHelper
end

app/helpers/states_helper.rb
# frozen_string_literal: true

# States Helper
module StatesHelper
end

app/views/cities/index.html.erb
<h1>Cities</h1>

<%= form_tag "/cities", class: 'search-form', method: "GET" do %>
  <span class="search-input-label"><%= label_tag :search_by_name %></span>
  <%= text_field_tag :search_by_name, params[:search_by_name], class: 'search-input' %>
  <span class="search-input-label"><%= label_tag :search_by_state %></span>
  <%= text_field_tag :search_by_state, params[:search_by_state], class: 'search-input' %>
  <%= submit_tag "Search", class: 'btn' %>
<% end %>
<% if @cities && @cities.length > 0 %>
    <table cellspacing="0" cellpadding="0">
        <tr>
            <th>Name</th>
            <th>State</th>
            <th>Capital</th>
        </tr>
        
        <% @cities.each do |city| %>
            <tr>
                <td><%= city.name %></td>
                <td><%= city.state.symbol %></td>
                <td><%= city.capital ? 'Yes' : 'No' %></td>
            </tr>
        <% end %>
    </table>
<% else %>
    <div class="table-no-results">No results found</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Embarca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="item"><%= link_to "States", states_path%></div>
      <div class="item"><%= link_to "Cities", cities_path%></div>
    </div>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/states/index.html.erb
<h1>States</h1>

<table cellspacing="0" cellpadding="0">
    <tr>
        <th>Name</th>
        <th>Symbol</th>
    </tr>
    <% @states.each do |state| %>
        <tr>
            <td><%= state.name %></td>
            <td><%= state.symbol %></td>
        </tr>
    <% end %>
</table>